version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perf-server
    restart: always
    ports:
      - "3001:3001"
    # This is the key configuration for Windows Docker Desktop to connect to XAMPP MySQL
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER_ENV=true
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=perf_db
      - NODE_ENV=development
      - DEBUG=*
    # Add command to run with more verbose output
    command: >
      sh -c "echo 'Attempting to connect to MySQL at host.docker.internal...' &&
             echo 'Initializing database...' &&
             node scripts/init-db.js &&
             echo 'Starting server...' &&
             node --unhandled-rejections=strict index.js"
    # Add healthcheck to verify server is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
